yarnPath: .yarn/releases/yarn-4.7.0.cjs
enableInlineBuilds: true
enableGlobalCache: false
globalFolder: ./node_modules/.yarn_global
cacheFolder: ./node_modules/.yarn_cache
compressionLevel: 0
nodeLinker: pnp
enableTelemetry: false
defaultSemverRangePrefix: ""

packageExtensions:
  "@emotion/utils@*":
    peerDependencies:
      "@emotion/sheet": "*"
