image: node:lts

before_script:
  - yarn install --immutable

test-compile:
  stage: deploy
  script:
    - yarn tsc --noEmit
    - yarn build
    - yarn lint

pages:
  stage: deploy
  script:
    - yarn build
  artifacts:
    paths:
      - public
  only:
    - master

sync:
  stage: .post
  script:
    - git remote add github https://github.com/alok0/wallclock1.git
    - git remote add gitlab https://gitlab-ci-token:${REPO_TOKEN}@gitlab.com/aloknull/wallclock.git
    - git pull github
    - git push gitlab
