image: node:lts

test-compile:
  stage: deploy
  needs: []
  script:
    - yarn install --immutable
    - yarn tsc --noEmit
    - yarn build
    - yarn lint

pages:
  stage: deploy
  needs: []
  script:
    - yarn install --immutable
    - yarn build
  artifacts:
    paths:
      - public
  only:
    - master

sync:
  stage: .pre
  needs: []
  script:
    - git remote add github https://github.com/alok0/wallclock1.git
    - git remote add gitlab $(node -e 'let u = new URL(process.env.CI_REPOSITORY_URL);u.password=process.env.REPO_TOKEN;process.stdout.write(u.toString());')
    - git remote -v
    - git fetch github
    - git reset --hard github/master
    - git push gitlab HEAD:master
