image: node:lts

before_script:
  - yarn install --immutable

test-compile:
  stage: deploy
  script:
    - yarn tsc --noEmit
    - yarn build
    - yarn lint

pages:
  stage: deploy
  script:
    - yarn build
  artifacts:
    paths:
      - public
  only:
    - master
