image: node:lts

before_script:
  - yarn install --immutable

test-compile:
  stage: deploy
  script:
    - yarn tsc --noEmit
    - yarn build
    - yarn lint

pages:
  stage: deploy
  script:
    - yarn build
  artifacts:
    paths:
      - public
  only:
    - master
  except:
    variables:
      - $ONLY_RENOVATE

renovate:
  only:
    - master
  stage: .pre
  trigger:
    forward:
      yaml_variables: true
      pipeline_variables: true
    include: ci/renovate.yml
