name: sync-trigger

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - uses: eic/trigger-gitlab-ci@v1
        with:
          project_id: 23402816
          ref_name: master
          token: ${{ secrets.GLP_TOKEN }}
